export const TABLE_DIMENSIONS = {
    STRIKE_PRICE_WIDTH: 100,
    LTP_WIDTH: 80,
    BUTTON_SECTION_WIDTH: 160,
    TOTAL_SECTION_WIDTH: 320, // LTP + BUTTON_SECTION + LTP
    PADDING_HORIZONTAL: 16,
    ROW_VERTICAL_PADDING: 12,
}; 